on:
  schedule:
    - cron: '0 15 * * *' ## UNCOMMENT THIS WHEN READY FOR AUTOMATION
  workflow_dispatch:


name: dailyCH4_mlr_BK ## POPULATE THIS WITH YOUR MODEL ID

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rqthomas/vera-rocker:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        shell: Rscript {0}
        run: |
          install.packages(c('pacman'))

      - name: Generate forecasts
        shell: Rscript {0}
        run: |
          source("model_code/Bibek_CH4/dailyCH4_mlr_BK.R") ## POPULATE THIS WITH THE PATH TO YOUR CODE
